-- Migration: 105_legal_azul_y_nuevas_politicas.sql
-- El logo real de GastroFlow es azul, no verde: el landing y las páginas
-- legales quedaron con un acento verde/índigo pálido inconsistente con el
-- login y el logo. Se corrige el color de landing a azul (igual que
-- login.css) y se agregan Política de Cookies y Política de Reembolsos,
-- más un refuerzo de Habeas Data en Privacidad y de cancelaciones en
-- Términos. Se usa CONCAT (no REPLACE) para no perder texto que un
-- superadmin ya haya personalizado en /admin/landing.

UPDATE landing_settings SET `value` = '#6366f1' WHERE `key` = 'color_primary';
UPDATE landing_settings SET `value` = '#4f46e5' WHERE `key` = 'color_primary_hover';

UPDATE landing_settings
SET `value` = CONCAT(`value`, '\n\n<h2>5. Derechos del Titular de los Datos (Habeas Data)</h2>\n<p>\n  De acuerdo con la Ley 1581 de 2012 y el Decreto 1377 de 2013, como titular de los datos personales usted tiene derecho a:\n</p>\n<ul>\n  <li>Conocer, actualizar y rectificar sus datos personales.</li>\n  <li>Solicitar prueba de la autorización otorgada para el tratamiento de sus datos.</li>\n  <li>Ser informado sobre el uso que se le ha dado a sus datos personales.</li>\n  <li>Presentar quejas ante la Superintendencia de Industria y Comercio (SIC) por infracciones a la ley de protección de datos.</li>\n  <li>Revocar la autorización y/o solicitar la supresión del dato, cuando no se respeten los principios, derechos y garantías constitucionales y legales.</li>\n  <li>Acceder de forma gratuita a sus datos personales que hayan sido objeto de tratamiento.</li>\n</ul>\n<p>\n  Para ejercer estos derechos puede escribir a <a href="mailto:privacidad@gastroflow.app">privacidad@gastroflow.app</a>. Las consultas se resolverán en un plazo máximo de 15 días hábiles y los reclamos en un plazo máximo de 15 días hábiles contados a partir del día siguiente a la fecha de su recibo (con un término inicial de respuesta de 2 días hábiles indicando el estado de la solicitud, según lo dispuesto en el artículo 14 de la Ley 1581 de 2012).\n</p>\n\n<h2>6. Cookies</h2>\n<p>\n  Este sitio usa cookies esenciales de sesión y, opcionalmente, cookies analíticas. El detalle de qué cookies se usan y cómo gestionarlas está en nuestra <a href="/legal/cookies">Política de Cookies</a>.\n</p>')
WHERE `key` = 'privacy_policy';

UPDATE landing_settings
SET `value` = CONCAT(`value`, '\n\n<h2>5. Cancelaciones y Reembolsos</h2>\n<p>\n  El manejo de cancelaciones de suscripción y reembolsos se rige por la <a href="/legal/reembolsos">Política de Reembolsos y Cancelación</a>.\n</p>')
WHERE `key` = 'terms_conditions';

INSERT IGNORE INTO landing_settings (`key`, `value`) VALUES
('cookies_policy', '<h2>1. ¿Qué son las cookies?</h2>\n<p>\n  Las cookies son pequeños archivos de texto que un sitio web guarda en su navegador para recordar información entre visitas. GastroFlow usa cookies únicamente en sus páginas públicas (landing, inicio de sesión, registro y documentos legales) — nunca dentro del sistema operativo interno del restaurante.\n</p>\n\n<h2>2. Cookies que usamos</h2>\n<p><strong>Esenciales (siempre activas, no requieren consentimiento):</strong></p>\n<ul>\n  <li><code>auth_token</code>: mantiene su sesión iniciada de forma segura (httpOnly). Sin ella no es posible usar el sistema.</li>\n</ul>\n<p><strong>Analíticas (opcionales, requieren su aceptación):</strong></p>\n<ul>\n  <li>Google Analytics (GA4): nos ayuda a entender cómo se usan nuestras páginas públicas para mejorarlas. Solo se activa si usted acepta el banner de cookies. Puede revocar su aceptación en cualquier momento borrando las cookies de su navegador.</li>\n</ul>\n\n<h2>3. Cómo gestionar sus preferencias</h2>\n<p>\n  Al visitar el sitio por primera vez, un banner le permite Aceptar o Rechazar las cookies analíticas. Su elección se guarda en su navegador y puede cambiarla borrando los datos de navegación de este sitio, lo que hará que el banner vuelva a aparecer.\n</p>\n\n<h2>4. Más información</h2>\n<p>\n  Para conocer cómo tratamos sus datos personales en general, consulte nuestra <a href="/legal/privacidad">Política de Privacidad</a>.\n</p>'),
('refund_policy', '<h2>1. Ciclo de facturación</h2>\n<p>\n  Las suscripciones a GastroFlow se cobran por adelantado, de forma mensual o anual según el plan contratado, a través de la pasarela de pagos Wompi.\n</p>\n\n<h2>2. Cancelación</h2>\n<p>\n  Puede cancelar su suscripción en cualquier momento desde el panel de administración de su cuenta. La cancelación detiene los cobros futuros, pero el servicio permanece activo hasta el final del periodo ya pagado.\n</p>\n\n<h2>3. Reembolsos</h2>\n<p>\n  Como regla general, los pagos ya realizados no son reembolsables, dado que dan acceso inmediato al Servicio durante todo el periodo facturado. Evaluamos excepciones caso por caso ante cobros duplicados por error técnico o fallas comprobadas del Servicio atribuibles a GastroFlow — en esos casos escríbanos a <a href="mailto:soporte@gastroflow.app">soporte@gastroflow.app</a>.\n</p>\n\n<h2>4. Impago y suspensión</h2>\n<p>\n  Si un cobro no se procesa correctamente, la cuenta cuenta con un periodo de gracia de 7 días antes de suspenderse. Durante la suspensión los datos del restaurante se conservan y el servicio se reactiva automáticamente al regularizar el pago.\n</p>');
